
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/upload-artifact@v2
        with:
          name: jmeter-scripts
          path: .

      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.3.1
        with:
          testFilePath: sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO -p PeakHourLoad.properties"
